name: PrizeCode
author: "jasonwynn10"
version: 0.1.0
api:
- 3.0.0-ALPHA3
main: jasonwynn10\Main
description: ""
commands:
  code:
    usage: "/code [reset]"
    permission: code
    description: ""
permissions:
  code:
    default: true